import type { Metadata } from "next";
import WuTangClient from "./WuTangClient";

export const metadata: Metadata = {
  title: "Wu-Tang Name Generator – Get Your Wu-Tang Clan Name",
  description:
    "Free Wu-Tang name generator — enter your real name and get your official Wu-Tang Clan name. Based on the Wu-Tang Name Generator formula.",
  keywords: ["wu tang name generator", "wu tang clan name", "wu-tang name", "rap name generator"],
  openGraph: {
    title: "Wu-Tang Name Generator – Get Your Wu-Tang Clan Name",
    description: "Enter your name and get your official Wu-Tang Clan name. Free, instant.",
    url: "https://webtoolswiki.com/wu-tang-name-generator",
  },
  alternates: { canonical: "https://webtoolswiki.com/wu-tang-name-generator" },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "Wu-Tang Name Generator",
  url: "https://webtoolswiki.com/wu-tang-name-generator",
  description: "Free Wu-Tang name generator — enter your real name and get your official Wu-Tang Clan name.",
  applicationCategory: "UtilityApplication",
  operatingSystem: "Any",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    { "@type": "Question", name: "How does the Wu-Tang name generator work?", acceptedAnswer: { "@type": "Answer", text: "Your name is generated by mapping the first letter of your first name to an adjective and the first letter of your last name to a noun, following the classic Wu-Tang Clan naming formula." } },
    { "@type": "Question", name: "Is this the official Wu-Tang name generator?", acceptedAnswer: { "@type": "Answer", text: "This is a fun fan-made generator inspired by the Wu-Tang Clan naming tradition. It's not officially affiliated with Wu-Tang Clan." } },
    { "@type": "Question", name: "Can I use my Wu-Tang name as a rap name?", acceptedAnswer: { "@type": "Answer", text: "Absolutely — use it as a stage name, social media handle, or just for fun at parties." } },
  ],
};

export default function WuTangPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <WuTangClient />
    </>
  );
}
