import type { Metadata } from "next";
import RapNameClient from "./RapNameClient";

export const metadata: Metadata = {
  title: "Rap Name Generator – Get Your Rapper Name",
  description:
    "Free rap name generator — get a cool rapper name instantly. Enter your real name or pick a random rap alias for fun or social media.",
  keywords: ["rap name generator", "rapper name generator", "hip hop name generator", "rap alias generator"],
  openGraph: {
    title: "Rap Name Generator – Get Your Rapper Name",
    description: "Get a cool rapper name instantly. Enter your real name or pick a random rap alias for fun or social media.",
    url: "https://webtoolswiki.com/rap-name-generator",
  },
  alternates: { canonical: "https://webtoolswiki.com/rap-name-generator" },
};

const faqItems = [
  {
    q: "How are rap names generated?",
    a: "Rap names are generated by combining your real name (or random words) with classic hip-hop naming conventions like 'Lil', 'Big', 'Young', 'MC', and style-specific suffixes.",
  },
  {
    q: "Can I use my rap name on social media?",
    a: "Yes! Your generated rap name is free to use anywhere — Instagram, TikTok, SoundCloud, or as a stage name.",
  },
  {
    q: "What makes a good rap name?",
    a: "The best rap names are short (1-3 words), easy to remember, reflect your personality or style, and have a nice rhythm when said out loud.",
  },
];

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "Rap Name Generator",
  url: "https://webtoolswiki.com/rap-name-generator",
  description: "Free rap name generator — get a cool rapper name instantly. Enter your real name or pick a random rap alias.",
  applicationCategory: "UtilityApplication",
  operatingSystem: "Any",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqItems.map(({ q, a }) => ({
    "@type": "Question",
    name: q,
    acceptedAnswer: { "@type": "Answer", text: a },
  })),
};

export default function RapNamePage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <RapNameClient faqItems={faqItems} />
    </>
  );
}
